# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout to Master
      uses: actions/checkout@master
      
    - name: Install Nuget
      uses: nuget/setup-nuget@v1
    
    - name: Nuget Restore
      run: nuget restore WavVisualize.sln
        
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Build project
      working-directory: WavVisualize
      run: msbuild WavVisualize.csproj
