# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup Nuget
    - uses: actions/checkout@master
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
    - run: nuget restore WavVisualize.sln
        
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Build project
      working-directory: WavVisualize
      run: msbuild WavVisualize.csproj
